services:
  # BACKEND SERVER
  myapp:
    container_name: ssl
    # restart: unless-stopped
    volumes:
      - ./your_quality_programmer:/code
      - static:/app/static
    build: .
    ports:
      - '8000:8000'
    command: >
      sh -c "
        python manage.py collectstatic --noinput
        python manage.py migrate --noinput
        python -m gunicorn --bind 0.0.0.0:8000 --workers 3 your_quality_programmer.wsgi:application
      "
    develop:
      watch:
        - action: sync
          path: ./your_quality_programmer
          target: /code
          ignore:
            - Dockerfile

  # NGINX SERVER
  nginx:
    container_name: ssl-proxy
    build: ./nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - static:/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - certbot_www:/var/www/certbot
      - certbot_etc:/etc/letsencrypt
    depends_on:
      - myapp

  # CERTBOT
  certbot:
    container_name: ssl-cert
    image: certbot/certbot
    volumes:
      - certbot_www:/var/www/certbot
      - certbot_etc:/etc/letsencrypt
    command: certonly --webroot --webroot-path=/var/www/certbot --email yourqualityprogrammer@gmail.com --agree-tos --no-eff-email --staging -d yourhonestprogrammer.com -d www.yourhonestprogrammer.com

volumes:
  static:
  certbot_www:
  certbot_etc:
