services:
  # BACKEND SERVER
  myapp:
    # restart: unless-stopped
    volumes:
      - ./your_quality_programmer:/code
      - static:/static
    build:
      context: ./your_quality_programmer
    ports:
      - '8000:8000'
    command: >
      bash -c "
      python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    develop:
      watch:
        - action: sync
          path: ./your_quality_programmer
          target: /code
          ignore:
            - Dockerfile

  # NGINX SERVER
  nginx:
    build: ./nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - certbot_www:/var/www/certbot
      - certbot_etc:/etc/letsencrypt
    depends_on:
      - myapp

  # CERTBOT
  certbot:
    image: certbot/certbot
    volumes:
      - certbot_www:/var/www/certbot
      - certbot_etc:/etc/letsencrypt
    command: certonly --webroot --webroot-path=/var/www/certbot --email your-email@example.com --agree-tos --no-eff-email --staging -d example.com -d www.example.com

volumes:
  static:
  certbot_www:
  certbot_etc: